_target_: models.unet.ResUNet
input_size: ${generator.input_size}
output_channels: ${generator.output_channels}
encoder_activation: ${generator.encoder_activation}
final_activation: ${generator.final_activation}
norm_layer: ${generator.norm_layer}
use_bilinear: ${generator.use_bilinear}
backbone: ${generator.backbone}
# attention_mechanism: ${generator.attention_mechanism}
# attention_layers: ${generator.attention_layers}
# use_learnable_positional_embeddings: ${generator.use_learnable_positional_embeddings}
# dropout: ${generator.dropout}
# attention_dropout: ${generator.attention_dropout}