defaults:
  - _self_

  # Models
  - generator_model: ResUNet
  - discriminator_model: NLayerDiscriminator

  # Optimizers
  - generator_optimizer: AdamW
  - discriminator_optimizer: AdamW

  # Schedulers
  - generator_scheduler: ExponentialLR
  - discriminator_scheduler: ExponentialLR

  # Callbacks
  - callbacks: null

  # Losses
  - adversarial_loss: BCEWithLogitsLoss

  # Metrics
  - train_metrics: null
  - val_metrics: null
  - test_metrics: StainMetrics
  - predict_metrics: null

  # Trainer
  - trainer: GAN_trainer

  # Data
  - datamodule: StainDataModule

  # Module
  - module: null

  # Transforms
  - HE_transforms: GAN_predict_transforms
  - IHC_transforms: GAN_predict_transforms
  - HE_augmentations: null
  - IHC_augmentations: null

  # Logger
  - logger: null

  # Wrapper
  - wrapper: PyramidLoss  # [PyramidLoss, PatchLoss, null]

  # Generator Loss
  - criterion: MSELoss  # [MSELoss, L1Loss]

train:
    # Resume from checkpoint
    resume_from_checkpoint: null

    # Generator
    backbone: resnet50

    # Optimizer
    lr: 5e-5
    weight_decay: 1e-5

    # Dataloader
    batch_size: 1
    num_workers: 8
    prefetch_factor: 2

    # Train
    accumulate_grad_batches: 1
    clip_grad_value: null
    max_epochs: 1
    min_epochs: 0

    # GAN
    condition_discriminator: true
    alternate_training: false
    train_generator_every_n_epochs: 1
    train_discriminator_every_n_epochs: 1
    start_training_generator_epoch: 0
    start_training_discriminator_epoch: 0

    # Metrics
    compute_metrics_on_gpu: true  # If cpu is setted, it will be computed on cpu

discriminator:
  input_nc: 6
  ndf: 64
  n_layers: 4
  norm_layer: batch
  no_antialias: false
  weight_norm: spectral
  compilation:
    enabled: false
    fullgraph: true

generator:
  input_size: [512, 512]
  output_channels: 3
  encoder_activation: relu
  final_activation: sigmoid
  norm_layer: instance
  use_bilinear: true
  backbone: resnet50
  compilation:
    enabled: true
    fullgraph: true

general:
    experiment_group: Thesis
    experiment_name: null
    job_type: test
    log_graph: false
    num_example_images: 0
    seed: 42
    matmul_precision: medium
    trainer_precision: 32-true
    deterministic: false
    benchmarking: true
    device: gpu
    verbose: false

    # Debugging
    log_gradients: false
    overfit_batches: 0
    detect_anomaly: false
    num_sanity_val_steps: 0
    enable_model_summary: false
    profiler: null
    max_dataset_size: 100

hydra:
  run:
    dir: null
